#!/bin/sh

# Upload tiles to Mapbox
docker run \
  --mount type=bind,source=${PWD}/app,target=/app \
  --mount type=bind,source=${PWD}/src,target=/usr/local/src \
  njmap /usr/local/src/upload-tiles.py

# Start serving application
cd app && python -m SimpleHTTPServer 8000