#!/bin/sh

# Remove containers created with the 'njmap' image
docker ps -a | grep 'njmap' | awk '{print $1}' | xargs docker rm

# Remove images tagged 'njmap'
#docker images -a | grep 'njmap' | awk '{print $3}' | xargs docker rmi -f dangling=true